# Generated by Django 6.0.2 on 2026-02-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='Untitled Event', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('concert', 'Concert'), ('conference', 'Conference'), ('private_party', 'Private Party'), ('charity', 'Charity / Fundraiser'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='special_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='enquiry', max_length=20),
        ),
    ]
