# Generated by Django 6.0.2 on 2026-02-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_quote_options_remove_quote_final_quote_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='api.event'),
        ),
        migrations.AddField(
            model_name='quote',
            name='special_requirements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
