# Generated by Django 6.0.2 on 2026-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quote_event_quote_special_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
