# Generated by Django 6.0.2 on 2026-02-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quoteitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.event'),
        ),
    ]
