# Generated by Django 6.0.2 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_payment_discount_event_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
