# Generated by Django 6.0.2 on 2026-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_up_to', models.PositiveIntegerField(help_text='Distance up to (km)')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Cost for this distance', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['distance_up_to'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='distance_from_ballinasloe',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in km', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='travel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
