# Generated by Django 6.0.2 on 2026-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_travelrate_event_distance_from_ballinasloe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
    ]
