# Generated by Django 6.0.2 on 2026-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_twofactorauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelrate',
            options={'ordering': ['distance_from', 'distance_to']},
        ),
        migrations.RemoveField(
            model_name='travelrate',
            name='distance_up_to',
        ),
        migrations.AddField(
            model_name='travelrate',
            name='distance_from',
            field=models.PositiveIntegerField(default=0, help_text='Distance from (km)'),
        ),
        migrations.AddField(
            model_name='travelrate',
            name='distance_to',
            field=models.PositiveIntegerField(default=9999, help_text='Distance to (km)'),
        ),
        migrations.AlterField(
            model_name='travelrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Cost for this distance range', max_digits=10),
        ),
    ]
