# Generated by Django 6.0.2 on 2026-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hall_available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
