# Generated by Django 6.0.2 on 2026-03-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
