# Generated by Django 6.0.2 on 2026-03-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_income_payer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='asset_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_active_asset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
    ]
