# Generated by Django 6.0.2 on 2026-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='receipt_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
