# Generated by Django 6.0.2 on 2026-03-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_expense_receipt_image_url_income_receipt_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email when a new contact message is received'),
        ),
    ]
