# Generated by Django 6.0.2 on 2026-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
