# Generated by Django 6.0.2 on 2026-03-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_expense_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='catering_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
