# Generated by Django 6.0.2 on 2026-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofile_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Company owner — included in profit distribution'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of net profit allocated to this owner', max_digits=5),
        ),
    ]
