# Generated by Django 6.0.2 on 2026-04-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_owner_fields_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.event'),
        ),
    ]
