# Generated by Django 6.0.2 on 2026-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cascade_expense_on_event_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='incomes/'),
        ),
    ]
