# Generated by Django 6.0.2 on 2026-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userprofile_add_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='enquiry', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], db_index=True, default='unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='Company owner — included in profit distribution'),
        ),
    ]
