# Generated by Django 6.0.2 on 2026-04-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenuitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
