# Generated by Django 6.0.2 on 2026-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_tip_amount_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='setup_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
