# Generated by Django 6.0.2 on 2026-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_setup_checklist_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checklist_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
