# Generated by Django 6.0.2 on 2026-06-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_userprofile_can_add_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_assets',
            field=models.BooleanField(default=False, help_text='Allow user to view the asset inventory'),
        ),
    ]
