# Generated by Django 6.0.2 on 2026-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_review_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
